version: '3'
services:
  zmifanva:
    image: 'olpa/zmifanva:1.0.0'
    ports:
      - '6543:6543'
    environment:
      MOSES_SERVER_JB2EN: 'http://jb2en:8080'
      MOSES_SERVER_EN2JB: 'http://en2jb:8080'
  jb2en:
    image: 'olpa/moses-zf-jb2en:1.0.0'
  en2jb:
    image: 'olpa/moses-zf-en2jb:1.0.0'
