version: '3'
services:
  zmifanva:
    image: 'olpa/zmifanva:1.0.0'
    ports:
      - '6543:6543'
    environment:
      MOSES_SERVER_JB2EN: 'http://jb-en:8080'
      MOSES_SERVER_EN2JB: 'http://en-jb:8080'
  jb-en:
    image: 'olpa/moses-zf-jb-en:1.0.0'
  en-jb:
    image: 'olpa/moses-zf-en-jb:1.0.0'
