FROM olpa/moses-tune

ARG RELEASE_TAG="1.0.0"

WORKDIR /build

RUN apt install -q -y python3-setuptools

RUN wget https://github.com/olpa/zmifanva/archive/refs/tags/${RELEASE_TAG}.zip \
  && unzip ${RELEASE_TAG}.zip \
  && mv zmifanva-${RELEASE_TAG} zmifanva \
  && cd zmifanva/web \
  && python3 setup.py install
