theme: jekyll-theme-midnight
baseurl: /lojban-mt
plugins:
  - jekyll-feed
author: Oleg Parashchenko
title: Lojban machine translation
description: News from lojban-mt project
github:
  repository_url: https://github.com/olpa/lojban-mt
